```{r}
library(tidyverse)

hd <- read.csv("data_files/historical_details.csv",
               fileEncoding="UTF-8-BOM",
               header =TRUE)
hd2 <- read.csv("data_files/historical_details_400-500.csv",
               fileEncoding="UTF-8-BOM",
               header =TRUE)
pi <- read.csv("data_files/patient_info.csv",
               fileEncoding="UTF-8-BOM",
               header =TRUE)
max_hour <- max(hd$hours_of_stay, na.rm=TRUE)
max_day <- max(hd$Day.on.Unit, na.rm=TRUE)
discharge_hours <- (pi$length_of_stay.days. * 24)
discharge_dates <- data.frame(patient_id = pi$patient_ID, discharge = discharge_hours)
#discharge_dates$discharge=as.numeric(levels(discharge_dates$discharge))[discharge_dates$discharge]
ggplot(discharge_dates, aes(x=discharge, y=reorder(patient_id, discharge))) +
  geom_point(color='red') +
geom_point(data=hd, aes(x=hours_of_stay, y=reorder(patient_ID, max_hour), size=distance^(1/.7)), inherit.aes=FALSE, alpha = 0.2) +
  geom_point(data=hd2, aes(x=hours_of_stay, y=reorder(patient_ID, max_hour), size=distance^(1/.7)), inherit.aes=FALSE, alpha = 0.2, color='blue') +
  scale_size_continuous(range = c(0.5, 10)) +
  scale_size(breaks = c(2000, 20000, 60000, 200000, 600000), range = c(0.5, 10)) +
  scale_y_discrete() +
  scale_x_continuous(breaks=seq(0,max_hour,24)) +
  ggtitle("Patient Ambulation Distance by Time") +
  xlab("Hour of Stay") + 
  ylab("Patient ID")
```
```{r}
library(tidyverse)

hd <- read.csv("data_files/historical_details.csv",
               fileEncoding="UTF-8-BOM",
               header =TRUE)
hd2 <- read.csv("data_files/historical_details_400-500.csv",
               fileEncoding="UTF-8-BOM",
               header =TRUE)
pi <- read.csv("data_files/patient_info.csv",
               fileEncoding="UTF-8-BOM",
               header =TRUE)
max_hour <- max(hd$hours_of_stay, na.rm=TRUE)
max_day <- max(hd$Day.on.Unit, na.rm=TRUE)
discharge_hours <- (pi$length_of_stay.days. * 24)
discharge_dates <- data.frame(patient_id = pi$patient_ID, discharge = discharge_hours)

ggplot(discharge_dates, aes(x=discharge, y=patient_id)) +
  geom_point(color='red') +
geom_point(data=hd, aes(x=hours_of_stay, y=patient_ID, size=distance^(1/.7)), inherit.aes=FALSE, alpha = 0.2) +
  geom_point(data=hd2, aes(x=hours_of_stay, y=patient_ID, size=distance^(1/.7)), inherit.aes=FALSE, alpha = 0.2, color='blue') +
  scale_size_continuous(range = c(0.5, 10)) +
  scale_size(breaks = c(2000, 20000, 60000, 200000, 600000), range = c(0.5, 10)) +
  scale_x_continuous(breaks=seq(0,max_hour,24)) +
  ggtitle("Patient Ambulation Distance by Time") +
  xlab("Hour of Stay") + 
  ylab("Patient ID")
```
```{r}
library(randomForest) # basic implementation

ambData <- read.csv("data_files/historical_details.csv",
               fileEncoding="UTF-8-BOM",
               header = TRUE)
set.seed(100)
trainRowCount <- floor(0.8 * nrow(ambData))
trainIndex <- sample(1:nrow(ambData), trainRowCount)
train <- ambData[trainIndex,]
test <- ambData[-trainIndex,]
predictorColumns <- c("ambulation", "hour_of_day", "Day.on.Unit", "distance", "duration", "speed", "hours_of_stay")
rf <- randomForest(train[predictorColumns], as.factor(train$max_hour), ntree=100, importance=TRUE)
print(rf)
predictions <- predict(rf, test[predictorColumns])
mean((test["max_hour"] - predictions)^2)
```
```{r}
library(tidyverse)

hdr <- read.csv("data_files/historical_details_readmitted.csv",
               fileEncoding="UTF-8-BOM",
               header =TRUE)
hdnr <- read.csv("data_files/historical_details_not_readmitted.csv",
               fileEncoding="UTF-8-BOM",
               header =TRUE)
pr <- read.csv("data_files/patients_readmitted.csv",
               fileEncoding="UTF-8-BOM",
               header =TRUE)
pnr <- read.csv("data_files/patients_not_readmitted.csv",
               fileEncoding="UTF-8-BOM",
               header =TRUE)
max_hour <- max(hdnr$hours_of_stay, na.rm=TRUE)

discharge_hours_r <- (pr$length_of_stay.days. * 24)
discharge_dates_r <- data.frame(patient_id = pr$patient_ID, discharge = discharge_hours_r)
discharge_hours_nr <- (pnr$length_of_stay.days. * 24)
discharge_dates_nr <- data.frame(patient_id = pnr$patient_ID, discharge = discharge_hours_nr)

ggplot() +
  geom_point(data=discharge_dates_r, aes(x=discharge, y=reorder(patient_id, discharge)), color = 'red') +
  geom_point(data=hdr, aes(x=hours_of_stay, y=reorder(patient_ID, max_hour), size=distance^(1/.7)), inherit.aes=FALSE, alpha = 0.2) +
#geom_point(data=discharge_dates_nr, aes(x=discharge, y=reorder(patient_id, discharge)), color='blue') +
#geom_point(data=hdnr, aes(x=hours_of_stay, y=reorder(patient_ID, max_hour), size=distance^(1/.7)), inherit.aes=FALSE, alpha = 0.2) +
  scale_size_continuous(range = c(0.5, 10)) +
  scale_size(breaks = c(2000, 20000, 60000, 200000, 600000), range = c(0.5, 10)) +
  scale_y_discrete() +
  scale_x_continuous(breaks=seq(0,max_hour,24)) +
  ggtitle("Patient Ambulation Distance by Time") +
  xlab("Hour of Stay") + 
  ylab("Patient ID")
```
```{r}
library(tidyverse)

pop <- read.csv("data_files/percent_of_patients.csv",
               fileEncoding="UTF-8-BOM",
               header =TRUE)
ggplot(data=pop, aes(x=Day, y=Percent)) + 
  geom_bar(stat="identity", fill="steelblue") +
  geom_text(aes(label=Percent), vjust=-0.3, size=3.5)+
  theme_minimal()
```